import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className="flex antialiased bg-zinc-100 dark:bg-black">
        <main className="flex-auto min-w-0 flex-col px-2 md:px-0">
          <Header />
          <div className="max-w-7xl mx-auto px-12">{children}</div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
